---

# Runtime
verbose: 7
secret:
  token: "lstbknd"

host: "hub.lstbknd.net"
issuer: "registry.lstbknd.net"
service: "hub.lstbknd.net"
key: "/opt/cert/hub/server/hub.lstbknd.net.key.pem"
auth_server: "https://api.lstbknd.net/auth"
access_token: "d424dd39e43a419c99b4abb88373bb30"

# Database and Messages broker
psql: "host=127.0.0.1 port=5431 user=lastbackend password=lastbackend dbname=registry sslmode=disable binary_parameters=yes"

api:
  host: 0.0.0.0
  port: 2955
  tls:
    insecure: false
    ca: "/opt/cert/registry/ca.pem"
    cert: "/opt/cert/registry/server.pem"
    key: "/opt/cert/registry/server-key.pem"
  blob_storage:
    type: "s3"
    endpoint: "127.0.0.1:9000"
    id: "V1EV9NJJQJDMQL43HJR9"
    secret: "scXdZkj2//SA9vCSwhr9uywSMuq/DrwY6MUoyOHg"
    bucket_name: "lb-bucket"
    ssl: false
  #    type: "azure"
  #    endpoint: "devcnrcustoragestandard.blob.core.windows.net"
  #    account: "devcnrcustoragestandard"
  #    key: "rGAinAq7+L+GRz2b65Zob+5VOmQeq2m6+CMkemzMMkHdNliycSqzI3Ggp17tTKGbJTi/+oz4iedV0uxW/y0AAA=="
  #    container: "lb-container"
  #    ssl: true

builder:
  tls:
    insecure: false
    ca: "/opt/cert/builder/ca.pem"
    cert: "/opt/cert/builder/client.pem"
    key: "/opt/cert/builder/client-key.pem"