---

# Runtime
verbose: 7
token: lstbknd
ssl: true
domain: "hub.lstbknd.net"

# Database and Messages broker
psql: "host=127.0.0.1 port=5431 user=lastbackend password=lastbackend dbname=registry sslmode=disable binary_parameters=yes"

git:
  uri: "git.lstbknd.net"

api:
  host: 0.0.0.0
  port: 2955
  tls:
    insecure: false
    cert: "/opt/ssl/cert.pem"
    key: "/opt/ssl/key.pem"

ctl:
  uuid: "85c6e91e-dd45-4b7b-8330-e2e3bd0a7bad"

builder:
  workers: 2
  logs: /opt/logs/
  uuid: "85c6e91e-dd45-4b7b-8330-e2e3bd0a7bac"
  docker:
    host: "172.17.0.1"
  extra_hosts:
  - "hub.lstbknd.net:172.17.0.1"
  - "api.lstbknd.net:172.17.0.1"
  cri:
    type: "docker"
  host: 0.0.0.0
  port: 2954
  tls:
    insecure: true
    cert: "/opt/ssl/cert.pem"
    key: "/opt/ssl/key.pem"

# Runtime
runtime:
  type: "docker"
#  docker:
#    certs: "/opt/ssl/"
